WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:135 There was an error managing chrome (error sending request for url (http://118.24.147.95:8086/chrome/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)); using driver found in the cache
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:base_mixin.py:65 【input】定位成功
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:base_mixin.py:65 【input】定位成功
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:base_mixin.py:65 【button】定位成功
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:func_template.py:23 步骤1：等待 ==> 开始执行...
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:func_template.py:28 关键字：【sleep】, 参数：(2,)
INFO     D:\Myset\auto_uitest_hjt\utils\logger\custom_logger.py:func_template.py:48 步骤1.等待  ==> 执行完毕!